### ISSUE TITLE
Invisible cursor

### ISSUE THREAD

**Issue by max107** [natecraddock/nvim-find#6]
Hi. Great plugin, great idea. Big thanks.
I have small problem with nvim-find. i dont see cursor for select file in prompt window.

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/862272/143081991-06adb8da-a674-472b-8a34-a5dcbde934ba.png">

**Comment by natecraddock** [comment]
Hi! Thanks for reporting. I think this might be a colorscheme problem, though I haven't looked closely.

Unfortunately I have actually stopped development on this plugin in favor of https://github.com/nvim-telescope/telescope.nvim. I originally created this for a better filepath matching algorithm than telescope, but I now realize I don't have the time to maintain a plugin like this.

So I am now working on https://github.com/natecraddock/zf, after finishing I will create a telescope extension wrapping zf for better filepath matching.
